import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const basePath = process.env.NODE_ENV === "production" ? "/isac" : "";
  return (
    <>
      <Head>
        <title>Smartvärd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={`${basePath}/logo.png`} />
        <link
          href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="homeText">
        <img src={`${basePath}/logo.png`} alt="bild på Smartvärds logotyp" />
        <h1>
          Maximera din uthyrning med oss på Smartvärd - Smidigt, Tryggt och
          Lönsamt
        </h1>
        <div>
          <span className="regular-text">
            Att hyra ut sin bostad kan vara ett fantastiskt sätt att tjäna extra
            pengar, men det kräver tid, kunskap och engagemang. Med
          </span>
          <span className="bold-text"> Smartvärd </span>
          <span className="regular-text">
            vid din sida slipper du stressen och kan njuta av alla fördelar med
            uthyrning utan att behöva tänka på detaljerna.
          </span>

          <br />
          <br />

          <span className="regular-text">
            Vill du få mer tid över och tryggheten i att din bostad hanteras av
            experter?
          </span>
          <span className="bold-text">
            {" "}
            Låt oss på Smartvärd göra jobbet - och njut av resultatet!
          </span>
        </div>
      </div>
      <div>
        <section id="firstSection">
          <h2>Om oss</h2>
          <div>
            <span className="regular-text">Välkommen till oss på </span>
            <span className="bold-text">Smartvärd </span>
            <span className="regular-text">
              - Din pålitliga partner inom Cohosting! Vi är ett nystartat
              företag som grundades 2024, med en vision att förändra och
              förenkla hur fastighetsägare och hyresvärdar hanterar sina
              korttidsuthyrningar. Vi brinner för att skapa fantastiska
              upplevelser både för våra kunder och deras gäster, genom att
              erbjuda skräddarsydda och effektiva lösningar.
            </span>
          </div>
          <div>
            <h3>Vår resa</h3>
            <span className="regular-text">
              Företaget grundades med ett starkt engagemang för fastigheter och
              hållbara affärslösningar. Med erfarenhet inom projektledning och
              en passion för gästservice, såg vi på Smartvärd en möjlighet att
              erbjuda en mer personlig och kvalitativ approach inom cohosting.
              Målet var klart - att skapa ett företag som inte bara hanterar
              bokningar och gäster, utan som också erbjuder ett helhetsgrepp som
              gör att fastighetsägare kan fokusera på det de gör bäst.
            </span>
          </div>
          <div>
            <h3>Vad gör vi?</h3>
            <span className="regular-text">
              På Smartvärd erbjuder vi en rad cohosting-tjänster som sträcker
              sig från att hantera bokningar och gästkommunikation till att ta
              hand om städning, underhåll och de små detaljerna som gör en stor
              skillnad. Vi arbetar nära våra kunder för att skapa en anpassad
              lösning som passar deras specifika behov - oavsett om du är ny
              inom korttidsuthyrning eller en erfaren värd.
            </span>
            <br />
            <br />
            <span className="regular-text">
              Vår vision är att förenkla och effektivisera hela processen, så
              att våra kunder kan maximera sina intäkter utan att tumma på
              kvaliteten. Vi tror på att bygga långsiktiga och hållbara
              relationer, både med våra kunder och deras gäster, genom att
              leverera pålitliga och professionella tjänster.
            </span>
          </div>
          <div>
            <h3>Vårt team</h3>
            <span className="regular-text">
              Vi är ett dedikerat team av cohosts som alla delar en passion för
              fastigheter och gästservice. Vi arbetar dagligen med att optimera
              och förbättra våra kunders uthyrningar. Vi samarbetar också med
              ett nätverk av pålitliga samarbetspartners, såsom städföretag och
              hantverkare, för att kunna erbjuda en komplett tjänst som håller
              högsta standard.
            </span>
          </div>
        </section>
        <section id="secondSection">
          <h2>Vår vision</h2>
          <div>
            <span className="regular-text">
              Vår ambition är att bli den främsta partnern för fastighetsägare
              som vill optimera sina korttidsuthyrningar, samtidigt som vi
              sätter gästens upplevelse i fokus. Vi vill erbjuda lösningar som
              gör cohosting enkelt, effektivt och lönsamt för alla parter.
            </span>
          </div>
          <div>
            <h3>Varför välja oss?</h3>
            <ul>
              <li>
                <span className="bold-text">Personlig service: </span>
                <span className="regular-text">
                  Vi anpassar oss efter dina behov och ser till att varje
                  uthyrning blir en framgång.
                </span>
              </li>
              <li>
                <span className="bold-text">Erfarenhet: </span>
                <span className="regular-text">
                  Vi har expertkunskap inom både cohosting och gästservice för
                  att säkerställa hög kvalitet.
                </span>
              </li>
              <li>
                <span className="bold-text">Helhetslösningar: </span>
                <span className="regular-text">
                  Vi tar hand om allt från bokningar till städning och
                  underhåll, så att du kan slappna av.
                </span>
              </li>
              <li>
                <span className="bold-text">Engagemang: </span>
                <span className="regular-text">
                  Vi är passionerade över att hjälpa dig skapa den bästa möjliga
                  upplevelsen för dina gäster och maximera dina intäkter.
                </span>
              </li>
            </ul>
          </div>
          <div>
            <br />
            <br />
            <span className="regular-text">
              Vi ser fram emot att få hjälpa dig att ta ditt korttidsuthyrnings
              projekt till nästa nivå!
            </span>
            <br />
            <br />
            <span className="regular-text">Vänliga hälsningar,</span>
            <br />
            <span className="bold-text">Teamet på Smartvärd</span>
          </div>
        </section>
        <section id="thirdSection">
          <h2>Kontakt</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vitae qui
            quos asperiores incidunt est molestias provident ducimus aut
            reiciendis sunt, inventore aspernatur dolor doloribus a! Veniam
            nobis, molestiae inventore voluptatum similique aliquid deserunt
            dolor facilis at, adipisci nam, totam hic. Cumque esse placeat
            repellendus itaque deleniti. Nulla quaerat sed deleniti ad quia unde
            minima veritatis! Dicta porro deleniti ipsa distinctio repellendus
            reiciendis voluptatibus nulla harum accusantium. Id debitis tempore
            iusto quo mollitia quas vitae. Harum at pariatur dignissimos error
            quas. Sint, obcaecati, tenetur, id quidem modi quae sit officia
            maxime nam explicabo recusandae suscipit perspiciatis magnam ratione
            dignissimos quia provident?
          </p>
        </section>
      </div>
    </>
  );
}
