import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Smartvärd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <section id="firstSection">
          <h2>First section</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vitae qui
            quos asperiores incidunt est molestias provident ducimus aut
            reiciendis sunt, inventore aspernatur dolor doloribus a! Veniam
            nobis, molestiae inventore voluptatum similique aliquid deserunt
            dolor facilis at, adipisci nam, totam hic. Cumque esse placeat
            repellendus itaque deleniti. Nulla quaerat sed deleniti ad quia unde
            minima veritatis! Dicta porro deleniti ipsa distinctio repellendus
            reiciendis voluptatibus nulla harum accusantium. Id debitis tempore
            iusto quo mollitia quas vitae. Harum at pariatur dignissimos error
            quas. Sint, obcaecati, tenetur, id quidem modi quae sit officia
            maxime nam explicabo recusandae suscipit perspiciatis magnam ratione
            dignissimos quia provident?
          </p>
        </section>
        <section id="secondSection">
          <h2>Second section</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vitae qui
            quos asperiores incidunt est molestias provident ducimus aut
            reiciendis sunt, inventore aspernatur dolor doloribus a! Veniam
            nobis, molestiae inventore voluptatum similique aliquid deserunt
            dolor facilis at, adipisci nam, totam hic. Cumque esse placeat
            repellendus itaque deleniti. Nulla quaerat sed deleniti ad quia unde
            minima veritatis! Dicta porro deleniti ipsa distinctio repellendus
            reiciendis voluptatibus nulla harum accusantium. Id debitis tempore
            iusto quo mollitia quas vitae. Harum at pariatur dignissimos error
            quas. Sint, obcaecati, tenetur, id quidem modi quae sit officia
            maxime nam explicabo recusandae suscipit perspiciatis magnam ratione
            dignissimos quia provident?
          </p>
        </section>
        <section id="thirdSection">
          <h2>Third section</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vitae qui
            quos asperiores incidunt est molestias provident ducimus aut
            reiciendis sunt, inventore aspernatur dolor doloribus a! Veniam
            nobis, molestiae inventore voluptatum similique aliquid deserunt
            dolor facilis at, adipisci nam, totam hic. Cumque esse placeat
            repellendus itaque deleniti. Nulla quaerat sed deleniti ad quia unde
            minima veritatis! Dicta porro deleniti ipsa distinctio repellendus
            reiciendis voluptatibus nulla harum accusantium. Id debitis tempore
            iusto quo mollitia quas vitae. Harum at pariatur dignissimos error
            quas. Sint, obcaecati, tenetur, id quidem modi quae sit officia
            maxime nam explicabo recusandae suscipit perspiciatis magnam ratione
            dignissimos quia provident?
          </p>
        </section>
      </div>
    </>
  );
}
